<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Rechaos.Core/Rechaos.Core.csproj" />
    <ProjectReference Include="../../src/Rechaos.Multiplayer/Rechaos.Multiplayer.csproj" />
  </ItemGroup>
</Project>
