<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Rechaos.Core/Rechaos.Core.csproj" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5.1" />
    <None Include="Assets/**/*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
