<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="RefurbishedDinosaurs.Core" Version="1.1.0-preview.shared-runtime" />
    <PackageReference Include="RefurbishedDinosaurs.Media.Audio" Version="1.1.0-preview.shared-runtime" />
    <EmbeddedResource Include="GameData/original-data.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RefurbishedDinosaurs.Media.Smacker" Version="1.0.1" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
  </ItemGroup>
</Project>
