<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <EmbeddedResource Include="GameData/original-data.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="RefurbishedDinosaurs.Media.Smacker" Version="1.0.1" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
  </ItemGroup>
</Project>
